<?php

/***************************************************************
 * Extension Manager/Repository config file
 *
 * Auto generated by Extension Builder
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
	'title' => 'Forminator',
	'description' => 'Utilities and improvements for extension typo3/cms-form',
	'category' => 'plugin',
	'author' => 'Steffen Kroggel',
	'author_email' => 'developer@steffenkroggel.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'clearCacheOnLoad' => 0,
	'version' => '12.4.0',
	'constraints' => [
		'depends' => [
            'typo3' => '12.4.99',
        ],
		'conflicts' => [
		],
		'suggests' => [
        ],
	],
];
