services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Madj2k\Forminator\:
    resource: '../Classes/*'

  Madj2k\Forminator\EventListener\ModifyFlexFormEvent:
    tags:
      -   name: event.listener
          identifier: 'flexParsing'
          event: TYPO3\CMS\Core\Configuration\Event\AfterFlexFormDataStructureParsedEvent

  Madj2k\Forminator\ViewHelpers\HCaptchaViewHelper:
    public: true
    arguments:
      $configurationService: '@Waldhacker\Hcaptcha\Service\ConfigurationService'
